x_speed=0;
y_speed=0;
movement_speed=4.5;
grav=1;
dashing=false;
dash_timer=0;
dash_duration=10; //frames the dash lasts
dash_cooldown_timer=0;
dash_cooldown=30; //frames before dash can be used again